
# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  # Kubernetes Master Server
  config.vm.define "osmaster" do |osmaster|
    osmaster.vm.box = "centos/7"
    osmaster.vm.hostname = "osmaster.example.com"
    osmaster.vm.network "private_network", ip: "172.16.16.100"
    osmaster.vm.provider "virtualbox" do |v|
      v.name = "osmaster"
      v.memory = 10240
      v.cpus = 4
      v.vmx["vhv.enable"] = "TRUE"
    end
  end
end
